### ISSUE TITLE
The Temple of Baalshamin download link is broken

### ISSUE THREAD

**Issue by vorg** [newpalmyra/newpalmyra.org#63]
The download link mentioned [here](http://www.newpalmyra.org/models/temple-of-baal-shamin/) is broken 
http://gandi0.fabricatorz.com:1337/temple-of-baalshamin.zip -> 404

**Comment by rejon** [comment]
Yeah, see this too: https://sketchfab.com/models/0c428b9c67254b50b2415a66042ec1ac#download

Is to download the model if logged into sketchfab. I think its running on nodejs on that server and need @barrythrew to comment on how to get that process going.

Actually, we need to do something because that server will go away.

Also, gandi0.newpalmyra.org is same as gandi0.fabricatorz.com

**Comment by christopheradams** [comment]
Closing in favor of #69. Thanks!
